### ISSUE TITLE
skips chapters

### ISSUE THREAD

**Issue by kolbdog3333** [FicHub/fichub.net#1]
when im downloading a fanfic it skips chapters and chapters are wrong
https://www.fanfiction.net/s/12715870/1/The-Loud-House-Revamped

**Comment by iridescent-beacon** [comment]
Sorry for the late reply here, apparently I wasn't _really_ subscribed to my own repository, but I believe I've fixed the notification issue.

Closing this as we talked on the discord and this was addressed as a one off.

The underlying issue, where it's impossible to tell whether an author has renumbered all chapters by inserting a new one at the beginning is still pending. It's possible this will be detectable if/when an official API ever materializes. Until then they'll likely be fixed as one-offs or by the eventual refreshing of all chapter content.

Thank you for the report in both places! :)
