### ISSUE TITLE
fichub.net doesn't get the last chapter from fanfiction.net

### ISSUE THREAD

**Issue by rr4pr** [FicHub/fichub.net#18]
Fou fics from fanfiction.net, last chapter added from 72 hours to 30 minutes — all of them exported without the last chapter (11-chapter story exported as 10-chapter etc).
Links:
[https://www.fanfiction.net/s/13693619/](url) (30 minutes)
[https://www.fanfiction.net/s/13594509/](url) (11 hours)
[https://www.fanfiction.net/s/13905146/](url) (18 hours)
[https://www.fanfiction.net/s/13872304/](url) (~72 hours)

**Comment by iridescent-beacon** [comment]
Hello! As I've attempted to explain in [the help section](https://fichub.net/#help) FicHub makes heavy use of caching to be a good netizen, so fics may be stale at times. Feel free to contact me here, IRC, or discord if you want something refreshed sooner than the background updater can get to it.

All four of those fics have been refreshed and you should be good to go. Happy reading!
