### ISSUE TITLE
Mention Source on 'Popular' page, mention 

### ISSUE THREAD

**Issue by xypha** [FicHub/fichub.net#2]
Current format:
`#rank [no of downloads] Name and author of fiction`
`Synopsis`
`xx words in xx chapter`

Suggestion - add a 4th line
**Source**: Name of source such as SpaceBattles/FanFiction/AO3, hyperlinked to fiction page

Reason for this suggestion: I have a habit of visiting the first chapter of a fiction to see if I would like the fiction and to check author notes, pairings, etc., before downloading an epub. Adding it to the popular page would help me and other like me.

creating an issue here because i am not on discord

**Comment by iridescent-beacon** [comment]
Thanks for the suggestion! Using issues here is completely acceptable :)

I've added the source link and updated the styling a bit to match the current cache page. The UI in general needs a lot of work, but the popular page in particular (which is one of the reasons it's not linked to anywhere). Feel free to let me know if you have any other suggestions.
