### ISSUE TITLE
how often are updates

### ISSUE THREAD

**Issue by kolbdog3333** [FicHub/fichub.net#24]
I am just wondering how long does it take for fichub to catch up with fanfiction.net on updates

**Comment by iridescent-beacon** [comment]
There's no simple answer to this question. For certain fandoms, I expect the mean time before fichub sees the update to be an the order of 24 hours or so -- but assuming that ffn actually gives consistent metadata and we're lucky it could be as low as a couple of minutes. Several of the update streams are heuristic based so there's no clear answer for those. There are currently some manual "catch all" jobs, but nothing that is currently run automatically on a schedule to give an upper bound, but I try to keep it < 1mo.

There's currently a bot on discord that will let you refresh a fic which I could easily extend to the irc channel if you're interested. Having a user initiated refresh feature on the website itself is issue #14 , so if you'd like to discuss that feature please hop over there.
