### ISSUE TITLE
Chapters uploaded in the last week won't download. 

### ISSUE THREAD

**Issue by puple-banananana** [FicHub/fichub.net#28]
I'm trying to download fics, but I noticed that any updates made in the last 7-8 days won't be in the downloaded file (fic has reached chapter 31 today, but if I try to download, only chapter 30 will show up.)

**Comment by iridescent-beacon** [comment]
Hello! As I've attempted to explain in [the help section](https://fichub.net/#help) FicHub makes heavy use of caching to be a good netizen, so fics may be stale at times. Is there anything I can do to clarify the wording there? 

Feel free to contact me here, IRC, or discord with the stories that are out of date if you want them refreshed sooner than the background updater can get to it.

There are definitely updates from the last week, so without further information there's nothing I can do.
