### ISSUE TITLE
FFnet export retains old content

### ISSUE THREAD

**Issue by AlexisNgyuen** [FicHub/fichub.net#30]
Hi! 

I found a weird issue while downloading this story: https://www.fanfiction.net/s/13569804/1/Strangers-On-a-Train

The issue is the content in Chapter 2 is not the same between the export and what's shown on the website. I suspect it might be because the author went and edited the story, and what's in the export is the old unedited version....? But this story was last updated in June 2021, more than 1 year before now, so it's strange that FicHub doesn't manage to download the latest version. Is there any fixes I could try?

**Comment by iridescent-beacon** [comment]
Hello!

This is a combination of a few things but the short answer is that rewrites will likely not be picked up automatically in the short term future. I'm happy to kick the backend when it's reported here, IRC, discord, or some other method of communication if you have a suggestion. 

This should hopefully be at least partially addressed when #14 and maybe #26 are.

I've refreshed the fic you mentioned so it should be good now if you export it again. I'm going to resolve this issue, but feel free to reopen it if something is still wrong with it or you have further suggestions :)
